name: Deploy Step Function

on:
  push:
    paths:
      - "state-machine.json"
      - ".github/workflows/main.yml"
    branches:
      - main

jobs:
  deploy-step-function:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate Step Function JSON
        run: |
          cat state-machine.json | jq empty

      - name: Deploy Step Function
        run: |
          aws stepfunctions update-state-machine \
            --state-machine-arn "${{ secrets.STATE_MACHINE_ARN }}" \
            --definition file://Main-StepFn.json
