name: Deploy Step Function and ECS Docker Images

on:
  push:
    branches:
      - main  # Runs on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push validator image
        run: |
          docker build -t ecs-validator-new ./ecs/validator
          docker tag ecs-validator-new:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ecs-validator-new:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ecs-validator-new:latest

      - name: Build, tag, and push transformer image
        run: |
          docker build -t ecs-transformer-new ./ecs/transformer
          docker tag ecs-transformer-new:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ecs-transformer-new:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ecs-transformer-new:latest

      - name: Validate Step Function JSON
        run: jq empty stepfunctions/MainStepFn.json

      - name: Deploy Step Function
        run: |
          aws stepfunctions update-state-machine \
            --state-machine-arn "${{ secrets.STATE_MACHINE_ARN }}" \
            --definition file://stepfunctions/MainStepFn.json
